site_name: Flesh and Blood | Rules and Policy
site_url: https://jjscott.nz/mkdocs-test/

site_description: The official rules and policy documents for the Flesh and Blood TCG.
site_author: Legedary Story Studios
copyright: ©2025 Legend Story Studios. All rights reserved.

theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.ico
  icon: material/menubook
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: lss-dark
      toggle:
        icon: material/brightness-4
        name: Dark mode
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: lss-light
      toggle:
        icon: material/brightness-7
        name: Light mode

markdown_extensions:
  - attr_list # custom anchors from markdown
  - meta # meta data for the page
  - toc:
      permalink: '§'
      toc_depth: 2  # Only show H1 and H2

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: 🇬🇧 English
          build: true
        - locale: ja
          name: 🇯🇵 Japanese
          build: true

hooks:
  - hooks/markdown_reference_preprocess.py
  - hooks/raw_txt_export.py
  - hooks/inject_icons.py

nav:
  - Comprehensive Rules:
    - Preface: 'cr/preface.md'
    - 1. Game Concepts: 'cr/01-game-concepts.md'
    - 2. Object Properties: 'cr/02-object-properties.md'
    - 3. Zones: 'cr/03-zones.md'
    - 4. Game Structure: 'cr/04-game-structure.md'
    - 5. Layers, Cards, and Abilities: 'cr/05-layers-cards-abilities.md'
    - 6. Effects: 'cr/06-effects.md'
    - 7. Combat: 'cr/07-combat.md'
    - 8. Keywords: 'cr/08-keywords.md'
    - 9. Additional Rules: 'cr/09-additional-rules.md'
    - Glossary: 'cr/glossary.md'
    - Acknowledgments: 'cr/acknowledgments.md'

  # - Tournament Rules and Policy:
  #   - 1. Game Concepts: 'trp/01-tournament-information.md'
  #   - 2. Roles and Responsibilities: 'trp/02-roles-and-responsibilities.md'
  #   - 3. Tournament Logistics: 'trp/03-tournament-logistics.md'