site_url: https://jjscott.nz/mkdocs-test/en/

# ENGLISH LANGUAGE CONFIGURATION
# ------------------------------

site_dir: ../../site/en/
docs_dir: ../../docs/en/

site_name: Flesh and Blood | Rules and Policy
site_description: The official rules and policy documents for the Flesh and Blood TCG.
site_author: Legedary Story Studios
copyright: © 2019 Legend Story Studios. All Rights Reserved.

nav:
  - Home: index.md
  - Comprehensive Rules:
    - Preface: 'cr/index.md'
    - 1. Game Concepts: 'cr/01-game-concepts.md'
    - 2. Object Properties: 'cr/02-object-properties.md'
    - 3. Zones: 'cr/03-zones.md'
    - 4. Game Structure: 'cr/04-game-structure.md'
    - 5. Layers, Cards, and Abilities: 'cr/05-layers-cards-abilities.md'
    - 6. Effects: 'cr/06-effects.md'
    - 7. Combat: 'cr/07-combat.md'
    - 8. Keywords: 'cr/08-keywords.md'
    - 9. Additional Rules: 'cr/09-additional-rules.md'
    - Glossary: 'cr/glossary.md'
    - Acknowledgments: 'cr/acknowledgments.md'

# ----------------------------------
# END ENGLISH LANGUAGE CONFIGURATION


# Set the version of each document
extra:
  cr:
    version: 2.10.1
  alternate:  
      # Switch to English
    - name: 🇬🇧 English
      link: /en/
      lang: en
    # Switch to Language
    - name: 🇯🇵 Japanese
      link: /ja/
      lang: ja
  
theme:
  language: en # ENGLISH LANGUAGE CONFIGURATION
  name: material
  custom_dir: ../../overrides
  favicon: assets/images/favicon.ico
  icon: material/menubook
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: lss-dark
      toggle:
        icon: material/brightness-4
        name: Dark mode
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: lss-light
      toggle:
        icon: material/brightness-7
        name: Light mode

markdown_extensions:
  - attr_list # custom anchors from markdown
  - meta # meta data for the page
  - toc:
      permalink: '§'
      toc_depth: 2  # Only show H1 and H2

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search:
      lang: en # ENGLISH LANGUAGE CONFIGURATION
  - macros

hooks:
  - ../../hooks/markdown_reference_preprocess.py
  - ../../hooks/raw_txt_export.py
  - ../../hooks/inject_icons.py
