# This is a basic workflow to help you get started with Actions

name: ci


# Run workflow on push to master or manual
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

# Required for gh-pages deployment
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repo under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # Setup python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Deploy using mk-docs
      - name: Deploy EN site to GitHub Pages
        run: mkdocs gh-deploy -f config/en/mkdocs.yml -d /en/ --force
      - name: Deploy JA site to GitHub Pages
        run: mkdocs gh-deploy -f config/ja/mkdocs.yml -d ja/ --force
