# This is a basic workflow to help you get started with Actions

name: ci


# Run workflow on push to master or manual
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

# Required for gh-pages deployment
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repo under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # Setup python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Build EN docs
      - name: Build EN site to '/site/en'
        run: mkdocs build -f config/en/mkdocs.yml -d ../../site/en
      
      # Build JA docs
      - name: Build JA site to '/site/ja'
        run: mkdocs build -f config/ja/mkdocs.yml  -d ../../site/ja

      # Push built EN pages to gh-pages branch
      - name: Deploy EN to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/en
          destination_dir: en
          publish_branch: gh-pages

      # Push built JA pages to gh-pages branch
      - name: Deploy JA to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/ja
          destination_dir: ja
          publish_branch: gh-pages

      # Push built txt pages to gh-pages branch
      - name: Deploy txt exports
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/txt
          destination_dir: txt
          keep_files: true