# This is a workflow to publish or overwrite a version of the documentation using mike.

name: publish_version

# Setup manual workflow with version inputs
on:
  workflow_dispatch:
    inputs:
        docsVersion:
          description: 'Version (e.g. 2.12)'
          required: true
        alias:
          description: 'Use `latest` if newest version' 

# Required for gh-pages deployment
permissions:
  contents: write

jobs:
  deploy:
    name: Publish next version with mike
    runs-on: ubuntu-latest

    steps:
      # Checks-out repo under $GITHUB_WORKSPACE
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # mike needs full history

      # Setup python and dependencies
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Runs a single command using the runners shell
      - name: Configure git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # Deploy using mike (versioning tool for mkdocs)
      - name: Deploy new version
        run: |
          mike deploy --push --update-aliases ${{ inputs.docsVersion }} ${{ inputs.alias }} 
